#!/bin/bash

set -u

GIT_CLONE_DESTINATION_ROOT_DIR="${HOME}/.ghq"

GITHUB_REPOSITORY_PATH="github.com/tanishi/dotfiles"

GIT_CLONE_DESTINATION_DIR="${GIT_CLONE_DESTINATION_ROOT_DIR}/${GITHUB_REPOSITORY_PATH}"
DOTFILES_REPOSITORY_URL="https://${GITHUB_REPOSITORY_PATH}"

IGNORE_FILE_LIST_NAME="${GIT_CLONE_DESTINATION_DIR}/etc/ignore_files.txt"
